-- =============================================================================
-- create_commentary_table.sql — AI 해설 저장 테이블 생성
-- =============================================================================
-- 실행 방법: psql -U racepulse -d racepulse -f scripts/create_commentary_table.sql
-- =============================================================================

-- commentary_type ENUM: 해설 종류
-- PRE  = 경주 전 사전 해설 (출전표 확정 후 생성)
-- POST = 경주 후 결과 해설 (결과 수집 후 생성)
do $$
begin
    create type commentary_type as enum ('PRE', 'POST');
exception
    when duplicate_object then null;
end $$;

-- =============================================================================
-- ai_commentary 테이블
-- GPT가 생성한 해설 텍스트를 DB에 영구 저장합니다.
-- Redis 캐시와 함께 사용하여 동일 경주 해설은 GPT를 한 번만 호출합니다.
-- =============================================================================
create table if not exists ai_commentary (
    id              bigint           generated by default as identity primary key,

    -- 어떤 경주의 해설인지 (races 테이블 FK)
    race_id         bigint           not null references races(id) on delete cascade,

    -- 해설 종류 (PRE=사전, POST=결과)
    type            commentary_type  not null,

    -- GPT가 생성한 해설 본문 (600~1200자)
    content         text             not null,

    -- 사용한 GPT 모델 이름 (예: "gpt-4o-mini", "gpt-4o")
    model_used      varchar(50)      not null default 'gpt-4o-mini',

    -- Redis 캐시 키 (중복 조회 시 캐시에서 바로 꺼냄)
    -- 예: pre_race:SC:20260508:1
    cache_key       varchar(100)     not null,

    -- 입력 토큰 / 출력 토큰 수 (비용 추적)
    prompt_tokens   integer,
    completion_tokens integer,

    -- GPT 해설이 생성된 시각
    generated_at    timestamp        not null default current_timestamp,

    -- 같은 경주의 같은 타입 해설은 1개만 저장
    unique (race_id, type)
);

-- 인덱스: race_id로 자주 조회하므로 인덱스 추가
create index if not exists idx_ai_commentary_race_id on ai_commentary (race_id);
create index if not exists idx_ai_commentary_type    on ai_commentary (race_id, type);

do $$
begin
    raise notice 'ai_commentary 테이블 생성 완료';
end $$;
