-- =============================================================================
-- create_ml_tables.sql — ML 피처 스토어 / 예측 / 모델 버전 테이블 생성
-- =============================================================================
-- 실행 방법: psql -U racepulse -d racepulse -f scripts/create_ml_tables.sql
-- =============================================================================

-- =============================================================================
-- ml_feature_store 테이블
-- =============================================================================
-- "피처 스토어(Feature Store)"란?
--   ML 모델이 학습/예측할 때 쓸 숫자 데이터(피처)를 미리 계산해서 저장해두는 창고입니다.
--   경주마다 20개+ 피처를 실시간으로 계산하면 너무 느리기 때문에
--   경주 전에 미리 계산해두고, 예측 요청이 오면 즉시 꺼내서 씁니다.
-- =============================================================================
create table if not exists ml_feature_store (
    -- 기본 키 (자동 증가)
    id              bigint      generated by default as identity primary key,

    -- race_entry_id = 어떤 출전마의 피처인지 (race_entries 테이블 FK)
    race_entry_id   bigint      not null references race_entries(id) on delete cascade,

    -- race_id = 어떤 경주인지 (빠른 조회를 위한 비정규화 컬럼)
    race_id         bigint      not null references races(id) on delete cascade,

    -- features = 계산된 피처 벡터 전체를 JSON으로 저장합니다.
    -- JSONB = JSON을 바이너리로 압축 저장하는 PostgreSQL 타입.
    --         일반 JSON보다 저장 공간이 작고 인덱스를 걸 수 있어 조회가 빠릅니다.
    -- 예: { "horse_win_rate_total": 0.25, "avg_rank_last5": 3.2, ... }
    features        jsonb       not null default '{}'::jsonb,

    -- feature_version = 피처 계산 로직 버전. 로직이 바뀌면 버전을 올려서 재계산합니다.
    feature_version varchar(20) not null default 'v1.0',

    -- 피처 계산 시각 (언제 계산됐는지 추적)
    calculated_at   timestamp   not null default current_timestamp,

    -- 같은 출전마에 대해 같은 버전 피처는 1개만 저장합니다.
    unique (race_entry_id, feature_version)
);

-- =============================================================================
-- predictions 테이블
-- =============================================================================
-- 모델이 계산한 착순 예측값과 확률을 저장합니다.
-- 모델 버전이 여러 개여도 각각 저장하므로 비교할 수 있습니다.
-- =============================================================================
create table if not exists predictions (
    id              bigint      generated by default as identity primary key,
    race_id         bigint      not null references races(id) on delete cascade,
    race_entry_id   bigint      not null references race_entries(id) on delete cascade,
    -- model_name = 예측에 사용한 모델 이름 (예: "xgboost_v1", "lgbm_v2")
    model_name      varchar(50) not null,
    -- predicted_rank = 예측 착순 (1~출전두수)
    predicted_rank  integer,
    -- win_prob = 1위 확률 (0.0 ~ 1.0)
    win_prob        decimal(6, 5),
    -- place_prob = 3위 이내 확률
    place_prob      decimal(6, 5),
    -- raw_score = 모델의 원시 점수 (정렬 기준으로 사용)
    raw_score       decimal(10, 6),
    -- model_version = 예측에 사용한 모델 파일 버전
    model_version   varchar(20) not null default 'v1.0',
    predicted_at    timestamp   not null default current_timestamp
);

-- =============================================================================
-- model_versions 테이블
-- =============================================================================
-- 학습된 ML 모델의 메타 정보를 기록합니다.
-- 언제 어떤 데이터로 학습했는지, 성능 지표는 얼마인지 추적합니다.
-- =============================================================================
create table if not exists model_versions (
    id              bigint      generated by default as identity primary key,
    model_name      varchar(50) not null,
    version         varchar(20) not null,
    -- model_path = 모델 파일 저장 경로 (예: "models/xgboost_v1.0.pkl")
    model_path      text,
    -- metrics = 학습 결과 지표 (정확도, NDCG 등)
    -- 예: { "accuracy": 0.42, "top3_accuracy": 0.68, "ndcg": 0.75 }
    metrics         jsonb       not null default '{}'::jsonb,
    -- train_start_date / train_end_date = 학습에 사용한 데이터 기간
    train_start_date date,
    train_end_date   date,
    is_active       boolean     not null default false,
    created_at      timestamp   not null default current_timestamp,
    unique (model_name, version)
);

-- 인덱스 (규칙 12: idx_테이블명_컬럼명)
create index if not exists idx_ml_feature_store_race_id    on ml_feature_store (race_id);
create index if not exists idx_ml_feature_store_entry_id   on ml_feature_store (race_entry_id);
create index if not exists idx_predictions_race_id         on predictions (race_id);
create index if not exists idx_predictions_entry_id        on predictions (race_entry_id);

do $$
begin
    raise notice 'ML 테이블 생성 완료 (ml_feature_store, predictions, model_versions)';
end $$;
