-- =============================================================================
-- V12: rival_records + horse_running_style 테이블 추가
-- =============================================================================
-- 4차 회의 확정사항:
--   rival_records      — 말 간 직접 대결 이력 (A vs B 전적)
--   horse_running_style — 말별 주행 스타일 (선행/추입/중간)
--
-- 두 테이블 모두 기존 race_results 데이터에서 자동 계산됩니다.
-- FastAPI POST /ml/rivals/calculate, POST /ml/running-style/calculate 로 채웁니다.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. rival_records — 말 간 직접 대결 이력
-- -----------------------------------------------------------------------------
-- horse_id_1 < horse_id_2 제약으로 양방향 중복을 방지합니다.
-- (A vs B)와 (B vs A)를 따로 저장하지 않고 하나만 저장합니다.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rival_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horse_id_1          BIGINT NOT NULL REFERENCES horses(id),
    horse_id_2          BIGINT NOT NULL REFERENCES horses(id),
    meet_code           VARCHAR(2)  NOT NULL,
    distance            INTEGER     NOT NULL,
    total_races         INTEGER     NOT NULL DEFAULT 0,
    horse1_wins         INTEGER     NOT NULL DEFAULT 0,
    horse2_wins         INTEGER     NOT NULL DEFAULT 0,
    horse1_avg_position NUMERIC(5, 2),
    horse2_avg_position NUMERIC(5, 2),
    last_race_id        BIGINT REFERENCES races(id),
    last_race_date      DATE,
    updated_at          TIMESTAMP   NOT NULL DEFAULT NOW(),

    -- horse_id_1 < horse_id_2 강제 — 양방향 중복 방지
    CHECK (horse_id_1 < horse_id_2),
    UNIQUE (horse_id_1, horse_id_2, meet_code, distance)
);

CREATE INDEX IF NOT EXISTS idx_rival_records_horse1
    ON rival_records (horse_id_1);

CREATE INDEX IF NOT EXISTS idx_rival_records_horse2
    ON rival_records (horse_id_2);


-- -----------------------------------------------------------------------------
-- 2. horse_running_style — 말별 주행 스타일
-- -----------------------------------------------------------------------------
-- 게이트 번호와 착순의 상관관계를 분석해 말의 주행 패턴을 분류합니다.
--   LEADER  : 선행 — 앞에서 달릴 때 성적이 좋음 (낮은 게이트 + 좋은 성적)
--   STALKER : 중간 추적 — 2~3위로 따라가다 막판 추월
--   CLOSER  : 추입 — 뒤에서 달릴 때 성적이 좋음 (높은 게이트 + 좋은 성적)
--   PRESSER : 선두 압박 — 2위로 바짝 붙어 선두 압박
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS horse_running_style (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horse_id            BIGINT      NOT NULL REFERENCES horses(id),
    style               VARCHAR(10) NOT NULL,  -- LEADER/STALKER/CLOSER/PRESSER
    track_type          VARCHAR(10) NOT NULL DEFAULT 'ALL',
    distance_category   VARCHAR(10) NOT NULL DEFAULT 'ALL',  -- SHORT/MIDDLE/LONG
    confidence_score    NUMERIC(5, 4),         -- 분류 신뢰도 (0~1)
    race_count          INTEGER     NOT NULL DEFAULT 0,
    avg_gate_no         NUMERIC(5, 2),         -- 평균 게이트 번호
    avg_inner_rank      NUMERIC(5, 2),         -- 낮은 게이트(1~4)에서 평균 순위
    avg_outer_rank      NUMERIC(5, 2),         -- 높은 게이트(9+)에서 평균 순위
    updated_at          TIMESTAMP   NOT NULL DEFAULT NOW(),

    UNIQUE (horse_id, track_type, distance_category)
);

CREATE INDEX IF NOT EXISTS idx_horse_running_style_horse
    ON horse_running_style (horse_id);
