-- =============================================================================
-- V13__phase3_schema.sql — Phase 3 기반 스키마 추가
-- =============================================================================
-- Flyway 규칙:
--   이미 실행된 V1~V12 마이그레이션은 체크섬 오류를 막기 위해 절대 수정하지 않습니다.
--   Phase 3에서 필요한 DB 구조는 새 버전 파일인 V13에만 추가합니다.
--
-- TIMESTAMPTZ 설명:
--   TIMESTAMP는 "시간값"만 저장하지만, TIMESTAMPTZ는 타임존까지 고려해 저장합니다.
--   사용자 동의 시각, 지갑 거래 시각, 변경 감지 시각처럼 운영 로그에 가까운 값은
--   서버/사용자 지역이 달라도 같은 순간을 비교할 수 있도록 TIMESTAMPTZ를 사용합니다.
-- =============================================================================

-- =============================================================================
-- 1. trainer_changes — 조교사 변경 이력
-- =============================================================================
-- 이 테이블은 말의 조교사가 바뀐 내역을 저장합니다.
-- GENERATED BY DEFAULT AS IDENTITY는 PostgreSQL이 id 값을 자동으로 1씩 증가시켜
-- 넣어 주는 기능입니다. 개발자가 매번 id를 직접 계산하지 않아도 됩니다.
-- REFERENCES는 외래키입니다. horse_id가 실제 horses 테이블의 말인지,
-- trainer_id가 실제 trainers 테이블의 조교사인지 DB가 직접 확인해 줍니다.
-- previous_change_id는 같은 테이블의 이전 변경 기록을 가리키는 자기참조 외래키입니다.
-- A 조교사 → B 조교사 → A 조교사처럼 변경 흐름을 체인으로 따라가기 위해 필요합니다.
CREATE TABLE IF NOT EXISTS trainer_changes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horse_id           BIGINT      NOT NULL REFERENCES horses(id),
    race_id            BIGINT      REFERENCES races(id),
    old_trainer_id     BIGINT      REFERENCES trainers(id),
    new_trainer_id     BIGINT      NOT NULL REFERENCES trainers(id),
    detected_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    change_date        DATE        NOT NULL,
    previous_change_id BIGINT      REFERENCES trainer_changes(id)
);

-- 인덱스는 자주 검색하는 컬럼에 붙이는 조회용 책갈피입니다.
-- 특정 말의 조교사 변경 이력을 빠르게 찾을 때 사용합니다.
CREATE INDEX IF NOT EXISTS idx_trainer_changes_horse
    ON trainer_changes (horse_id);

-- 특정 경주에서 발생한 조교사 변경 이력을 빠르게 찾을 때 사용합니다.
CREATE INDEX IF NOT EXISTS idx_trainer_changes_race
    ON trainer_changes (race_id);


-- =============================================================================
-- 2. equipment_changes — 장비 변경 이력
-- =============================================================================
-- 블링커, 안장, 편자 같은 장비 변경을 저장합니다.
-- old_value와 new_value를 분리해 저장하면 "무엇에서 무엇으로 바뀌었는지"를
-- UI와 ML 피처에서 모두 명확히 사용할 수 있습니다.
-- blinker_first_time은 블링커를 처음 착용하는 경우를 따로 표시하는 ML 피처입니다.
CREATE TABLE IF NOT EXISTS equipment_changes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horse_id           BIGINT      NOT NULL REFERENCES horses(id),
    race_id            BIGINT      REFERENCES races(id),
    equipment_type     VARCHAR(20) NOT NULL,
    old_value          VARCHAR(50),
    new_value          VARCHAR(50) NOT NULL,
    detected_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    change_date        DATE        NOT NULL,
    blinker_first_time BOOLEAN     NOT NULL DEFAULT FALSE,
    previous_change_id BIGINT      REFERENCES equipment_changes(id)
);

-- 특정 말의 장비 변경 이력을 빠르게 조회하기 위한 인덱스입니다.
CREATE INDEX IF NOT EXISTS idx_equipment_changes_horse
    ON equipment_changes (horse_id);

-- 특정 경주에서 발생한 장비 변경 이력을 빠르게 조회하기 위한 인덱스입니다.
CREATE INDEX IF NOT EXISTS idx_equipment_changes_race
    ON equipment_changes (race_id);


-- =============================================================================
-- 3. user_wallets — 편자 지갑
-- =============================================================================
-- Freemium 기능에서 사용하는 가상 재화 지갑입니다.
-- user_id에 UNIQUE를 둔 이유는 "한 유저는 지갑 하나만 가진다"는 1:1 관계를
-- DB 레벨에서 강제하기 위해서입니다.
-- ON DELETE CASCADE는 users 행이 삭제될 때 연결된 지갑도 같이 삭제한다는 뜻입니다.
-- 회원 탈퇴 후 고아 데이터가 남지 않도록 하기 위한 설정입니다.
-- CHECK 제약조건은 잔액이 음수가 되는 잘못된 데이터를 DB가 막도록 합니다.
CREATE TABLE IF NOT EXISTS user_wallets (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                    UUID        NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    event_horseshoe            INTEGER     NOT NULL DEFAULT 0 CHECK (event_horseshoe >= 0),
    event_horseshoe_expires_at TIMESTAMPTZ,
    paid_horseshoe             INTEGER     NOT NULL DEFAULT 0 CHECK (paid_horseshoe >= 0),
    hay                        INTEGER     NOT NULL DEFAULT 0 CHECK (hay >= 0),
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- user_id로 지갑을 찾는 API가 자주 호출되므로 인덱스를 둡니다.
-- UNIQUE 제약도 내부적으로 인덱스를 만들지만, 규칙에 맞는 명시적 이름으로도 남깁니다.
CREATE INDEX IF NOT EXISTS idx_user_wallets_user
    ON user_wallets (user_id);


-- =============================================================================
-- 4. wallet_transactions — 편자 거래 내역
-- =============================================================================
-- 지갑 잔액은 현재 상태이고, 거래 내역은 "왜 잔액이 바뀌었는지"를 추적하는 감사 로그입니다.
-- 이 테이블은 환불, 소비 취소, 관리자 지급 같은 운영 이슈를 확인해야 하므로
-- 삭제하지 않고 계속 쌓는 방식으로 사용합니다.
-- amount는 양수면 획득, 음수면 소비입니다. 그래서 amount에는 0 금지 CHECK를 둡니다.
CREATE TABLE IF NOT EXISTS wallet_transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    transaction_type VARCHAR(30)  NOT NULL,
    currency_type    VARCHAR(10)  NOT NULL,
    amount           INTEGER      NOT NULL CHECK (amount <> 0),
    balance_after    INTEGER      NOT NULL CHECK (balance_after >= 0),
    description      TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- 특정 유저의 거래 내역 화면에서 user_id 조건으로 빠르게 조회합니다.
CREATE INDEX IF NOT EXISTS idx_wallet_tx_user
    ON wallet_transactions (user_id);

-- 출석, 광고, 결제, 소비 등 거래 종류별 통계를 빠르게 집계할 때 사용합니다.
CREATE INDEX IF NOT EXISTS idx_wallet_tx_type
    ON wallet_transactions (transaction_type);

-- 최근 거래 내역을 시간순으로 보여 줄 때 created_at 정렬을 빠르게 만듭니다.
CREATE INDEX IF NOT EXISTS idx_wallet_tx_created
    ON wallet_transactions (created_at);


-- =============================================================================
-- 5. users 테이블 — 개인정보보호법 동의 컬럼 추가
-- =============================================================================
-- ALTER TABLE ... ADD COLUMN IF NOT EXISTS를 쓰는 이유:
--   개발 DB에서 같은 마이그레이션을 수동으로 일부 적용했거나,
--   환경별 스키마가 조금 달라도 컬럼 중복 오류 없이 안전하게 넘어가기 위해서입니다.
--   Flyway는 보통 한 번만 실행되지만, 로컬 개발 환경에서는 재실행 안전성이 중요합니다.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS marketing_agreed BOOLEAN NOT NULL DEFAULT FALSE;

-- 이용약관 동의는 필수값이지만, 기존 회원 데이터가 이미 있으므로 처음에는 NULL을 허용합니다.
-- 이후 애플리케이션에서 재동의 팝업을 통해 값을 채우는 방식으로 운영합니다.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS terms_agreed_at TIMESTAMPTZ;

-- 약관이 업데이트되면 terms_version을 비교해 재동의가 필요한지 판단합니다.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS terms_version VARCHAR(10);


-- =============================================================================
-- 6. ai_commentary 테이블 — AI 해설 품질 관리 컬럼 추가
-- =============================================================================
-- 품질 점수는 0~100 범위만 허용합니다.
-- CHECK 제약조건을 두면 애플리케이션 버그로 120점, -5점 같은 값이 들어가는 것을 막습니다.
ALTER TABLE ai_commentary
    ADD COLUMN IF NOT EXISTS quality_score SMALLINT CHECK (quality_score BETWEEN 0 AND 100);

-- 사전 해설과 결과 해설은 temperature를 다르게 쓰므로 실제 사용값을 저장합니다.
-- NUMERIC(3, 2)는 0.70처럼 전체 3자리, 소수 2자리 숫자를 뜻합니다.
ALTER TABLE ai_commentary
    ADD COLUMN IF NOT EXISTS temperature_used NUMERIC(3, 2);

-- 사행성 필터나 품질 검증 실패로 재생성한 횟수를 저장합니다.
-- 기본값 0은 "재시도 없이 한 번에 생성됨"을 뜻합니다.
ALTER TABLE ai_commentary
    ADD COLUMN IF NOT EXISTS retry_count SMALLINT NOT NULL DEFAULT 0;

-- GPT API 응답 시간을 밀리초 단위로 저장해 느린 요청을 추적합니다.
ALTER TABLE ai_commentary
    ADD COLUMN IF NOT EXISTS generation_ms INTEGER;
