-- =============================================================================
-- RacePulse 기본 경마 조회 테이블 생성
-- =============================================================================
-- 왜 이 파일이 필요한가?
-- application-dev.yaml에서 ddl-auto=validate를 사용하고 있으므로
-- 스프링 부트 실행 전에 Flyway가 테이블을 먼저 만들어줘야 앱이 정상 기동됩니다.
-- =============================================================================

create table if not exists racecourses (
    id bigint generated by default as identity primary key,
    meet_code varchar(10) not null unique,
    name varchar(100) not null,
    location varchar(255) not null,
    track_types jsonb not null default '[]'::jsonb,
    created_at timestamp not null default current_timestamp
);

do $$
begin
    create type track_condition as enum ('DRY', 'WET', 'HUMID', 'SATURATED');
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type race_status as enum ('SCHEDULED', 'COMPLETED', 'CANCELLED');
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type race_grade as enum ('일반', '중요', '특별', '국제');
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type pace_scenario as enum ('FAST', 'MODERATE', 'SLOW', 'CONTESTED');
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type pace_advantage as enum ('FRONT', 'STALKER', 'CLOSER');
exception
    when duplicate_object then null;
end $$;

create table if not exists races (
    id bigint generated by default as identity primary key,
    meet_code varchar(10) not null,
    rc_date date not null,
    race_no integer not null,
    race_name varchar(150) not null,
    distance integer not null,
    track_type varchar(50),
    track_condition track_condition,
    prize_money bigint,
    weather varchar(50),
    start_time time,
    status race_status not null,
    race_class varchar(50),
    race_grade race_grade,
    front_count integer,
    pace_scenario pace_scenario,
    pace_advantage pace_advantage,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists horses (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    eng_name varchar(100),
    birth_year integer,
    sex varchar(20),
    color varchar(50),
    origin varchar(50),
    father_name varchar(100),
    mother_name varchar(100),
    owner varchar(100),
    meet_code varchar(10) not null,
    rating_1 numeric(10, 2),
    rating_2 numeric(10, 2),
    rating_3 numeric(10, 2),
    rating_4 numeric(10, 2),
    coat_color varchar(50),
    body_type varchar(50),
    photo_url text,
    thumbnail_url text,
    is_active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create index if not exists idx_races_meet_code_rc_date on races (meet_code, rc_date);
create index if not exists idx_races_status on races (status);
create index if not exists idx_horses_meet_code on horses (meet_code);
create index if not exists idx_horses_name on horses (name);

insert into racecourses (meet_code, name, location, track_types)
values
    ('SC', '서울경마공원', '경기도 과천시', '["잔디", "모래"]'::jsonb),
    ('BU', '부산경남경마공원', '부산광역시 강서구', '["모래"]'::jsonb),
    ('JJ', '제주경마공원', '제주특별자치도 제주시', '["잔디", "모래"]'::jsonb)
on conflict (meet_code) do nothing;
