-- =============================================================================
-- V2__create_auth_tables.sql — 회원/인증 관련 테이블 생성
-- =============================================================================
-- 왜 새 파일인가?
-- Flyway 규칙(PROJECT_RULES 규칙 13): 한번 실행된 V1__ 파일은 절대 수정 금지.
-- 새 기능은 반드시 새 버전 파일(V2__)로 추가합니다.
-- =============================================================================

-- =============================================================================
-- auth_provider ENUM: 로그인 방식 구분
-- LOCAL = 이메일+비밀번호 직접 가입
-- KAKAO = 카카오 소셜 로그인
-- =============================================================================
do $$
begin
    create type auth_provider as enum ('LOCAL', 'KAKAO');
exception
    when duplicate_object then null;
end $$;

-- =============================================================================
-- user_role ENUM: 유저 권한
-- USER  = 일반 회원
-- ADMIN = 관리자
-- =============================================================================
do $$
begin
    create type user_role as enum ('USER', 'ADMIN');
exception
    when duplicate_object then null;
end $$;

-- =============================================================================
-- user_tier ENUM: 구독 등급
-- FREE = 무료 플랜
-- PRO  = 유료 플랜
-- =============================================================================
do $$
begin
    create type user_tier as enum ('FREE', 'PRO');
exception
    when duplicate_object then null;
end $$;

-- =============================================================================
-- users 테이블
-- 이메일 회원과 카카오 소셜 회원을 함께 저장합니다.
-- 카카오 회원은 password가 NULL이고 kakao_id가 채워집니다.
-- =============================================================================
create table if not exists users (
    -- UUID = 전 세계적으로 유일한 128비트 ID. 숫자 ID보다 예측이 어려워 보안에 좋습니다.
    id              uuid         primary key default gen_random_uuid(),
    email           varchar(255) not null unique,
    -- 카카오 유저는 비밀번호가 없으므로 nullable로 설정합니다.
    password        varchar(255),
    -- 카카오에서 발급한 유저 고유 숫자 ID (문자열로 저장)
    kakao_id        varchar(100) unique,
    auth_provider   auth_provider not null default 'LOCAL',
    nickname        varchar(50)  not null,
    role            user_role    not null default 'USER',
    tier            user_tier    not null default 'FREE',
    created_at      timestamp    not null default current_timestamp,
    updated_at      timestamp    not null default current_timestamp
);

-- =============================================================================
-- refresh_tokens 테이블
-- JWT Refresh Token을 DB에 저장하여 탈취 감지(Token Family)를 구현합니다.
--
-- [Token Family 개념]
-- 로그인할 때 family_id를 하나 생성합니다.
-- Refresh Token을 쓸 때마다 is_used=true로 표시하고 새 토큰을 발급합니다.
-- 만약 이미 used=true인 토큰으로 요청이 오면 → 탈취된 것으로 판단하고
-- 해당 family_id의 모든 토큰을 무효화하여 강제 로그아웃시킵니다.
-- =============================================================================
create table if not exists refresh_tokens (
    id          bigint      generated by default as identity primary key,
    -- 어느 유저의 토큰인지 연결
    user_id     uuid        not null references users(id) on delete cascade,
    -- 실제 토큰 값을 그대로 저장하면 DB가 털렸을 때 위험합니다.
    -- SHA-256 해시로 변환해서 저장하고, 비교도 해시끼리 합니다.
    token_hash  varchar(64) not null unique,
    -- family_id: 같은 로그인 세션에서 발급된 토큰들을 묶는 그룹 ID
    family_id   uuid        not null,
    -- 이 토큰이 이미 사용됐는지 여부 (사용 후 true로 변경)
    is_used     boolean     not null default false,
    -- 토큰 만료 시각
    expires_at  timestamp   not null,
    created_at  timestamp   not null default current_timestamp
);

-- 인덱스: 자주 조회하는 컬럼에 인덱스를 추가하면 쿼리가 빨라집니다.
-- 규칙 12: 인덱스 네이밍 = idx_테이블명_컬럼명
create index if not exists idx_users_email         on users (email);
create index if not exists idx_users_kakao_id      on users (kakao_id);
create index if not exists idx_refresh_tokens_user on refresh_tokens (user_id);
create index if not exists idx_refresh_tokens_fam  on refresh_tokens (family_id);
