-- =============================================================================
-- V3__create_push_tables.sql — Web Push 알림 관련 테이블 생성
-- =============================================================================
-- Web Push 알림이란?
--   브라우저를 닫아도 알림이 오는 기술입니다.
--   앱 알림처럼 PC/모바일 브라우저에 알림창이 뜹니다.
--
-- 동작 순서:
--   1) 브라우저가 구독 정보(endpoint + 암호화 키)를 우리 서버에 보냅니다.
--   2) 우리 서버가 이 정보를 push_subscriptions 테이블에 저장합니다.
--   3) 경주 시작 같은 이벤트가 발생하면 저장된 정보로 Push 서버에 메시지를 보냅니다.
--   4) Push 서버(Google/Mozilla)가 브라우저에 알림을 전달합니다.
-- =============================================================================

-- =============================================================================
-- notification_type ENUM: 알림 유형
-- RACE_START    = 경주 시작 알림 (경주 10분 전)
-- JOCKEY_CHANGE = 기수 변경 알림 (출전표 변경 시)
-- RESULT        = 경주 결과 알림 (경주 종료 후)
-- =============================================================================
do $$
begin
    create type notification_type as enum ('RACE_START', 'JOCKEY_CHANGE', 'RESULT');
exception
    when duplicate_object then null;
end $$;

-- =============================================================================
-- push_subscriptions 테이블
-- 브라우저가 보내온 구독 정보(endpoint + 암호화 키)를 저장합니다.
--
-- 컬럼 설명:
--   endpoint  = 브라우저마다 고유한 Push 서버 URL (여기로 메시지를 보냅니다)
--   p256dh_key = 메시지를 암호화할 때 사용하는 공개키 (Base64 인코딩)
--   auth_key  = 메시지 인증에 사용하는 추가 키 (Base64 인코딩)
--   user_agent = 어느 브라우저/기기에서 구독했는지 기록
-- =============================================================================
create table if not exists push_subscriptions (
    id          bigint      generated by default as identity primary key,
    -- 어느 유저의 구독인지 연결합니다.
    user_id     uuid        not null references users(id) on delete cascade,
    -- endpoint = 브라우저 고유 Push 서버 URL. 이 주소로 메시지를 보내면 해당 브라우저에 도착합니다.
    endpoint    text        not null unique,
    -- p256dh_key = ECDH 공개키. 메시지를 암호화하여 전송할 때 사용합니다.
    p256dh_key  varchar(255) not null,
    -- auth_key = 메시지 인증 키. 브라우저가 진짜 메시지인지 검증할 때 사용합니다.
    auth_key    varchar(255) not null,
    -- 어떤 브라우저/OS에서 구독했는지 기록합니다. (Chrome/Firefox/Safari 등)
    user_agent  varchar(500),
    created_at  timestamp   not null default current_timestamp
);

-- =============================================================================
-- notification_settings 테이블
-- 유저별로 어떤 알림을 받을지 설정을 저장합니다.
-- 기본값: 모든 알림 ON
-- =============================================================================
create table if not exists notification_settings (
    id          bigint          generated by default as identity primary key,
    user_id     uuid            not null references users(id) on delete cascade,
    -- 알림 유형 (RACE_START / JOCKEY_CHANGE / RESULT)
    type        notification_type not null,
    -- true = 알림 받기 ON, false = 알림 받기 OFF
    is_enabled  boolean         not null default true,
    created_at  timestamp       not null default current_timestamp,
    updated_at  timestamp       not null default current_timestamp,
    -- 같은 유저가 같은 알림 유형을 중복 등록하지 못하도록 유니크 제약을 겁니다.
    unique (user_id, type)
);

-- 인덱스: user_id 로 자주 조회하므로 인덱스를 추가합니다.
-- 규칙 12: 인덱스 네이밍 = idx_테이블명_컬럼명
create index if not exists idx_push_subscriptions_user    on push_subscriptions (user_id);
create index if not exists idx_notification_settings_user on notification_settings (user_id);
