-- =============================================================================
-- V5: 마이페이지 즐겨찾기/사용자 설정 테이블
-- =============================================================================

create table if not exists user_favorites (
    id bigint generated by default as identity primary key,
    user_id uuid not null references users(id) on delete cascade,
    target_type varchar(20) not null,
    target_id bigint not null,
    created_at timestamp not null default current_timestamp,
    unique (user_id, target_type, target_id)
);

create table if not exists user_preferences (
    user_id uuid primary key references users(id) on delete cascade,
    theme varchar(20) not null default 'dark',
    nickname varchar(50),
    updated_at timestamp not null default current_timestamp
);

create index if not exists idx_user_favorites_user on user_favorites (user_id);
create index if not exists idx_user_favorites_target on user_favorites (target_type, target_id);
