-- =============================================================================
-- V6: Phase 2 — ML 예측 / 경주 출전 / 통계 테이블 (11개)
-- =============================================================================
-- 포함 테이블:
--   1. jockeys              — 기수
--   2. trainers             — 조교사
--   3. race_entries         — 경주 출전 정보 (말+기수+조교사 연결)
--   4. race_results         — 실제 경주 결과
--   5. horse_stats          — 말 누적 통계 (avg_finish_position, top3_rate 등)
--   6. jockey_stats         — 기수 누적 통계
--   7. trainer_stats        — 조교사 누적 통계
--   8. odds_history         — 배당률 이력
--   9. ml_model_versions    — ML 모델 버전 관리
--  10. ml_feature_store     — ML 피처 스토어 (JSONB + 핵심 컬럼)
--  11. race_predictions     — 예측 결과 (Monte Carlo 포함)
-- =============================================================================


-- =============================================================================
-- 1. jockeys — 기수
-- =============================================================================
create table if not exists jockeys (
    id              bigint      generated by default as identity primary key,
    -- 마사회 API 기수 코드 (meet_code 별로 고유)
    jockey_code     varchar(20) not null,
    meet_code       varchar(10) not null,
    name            varchar(50) not null,
    eng_name        varchar(100),
    birth_year      integer,
    debut_year      integer,
    -- 소속 경마장 (SC/BU/JJ)
    affiliation     varchar(10),
    photo_url       text,
    is_active       boolean     not null default true,
    created_at      timestamp   not null default current_timestamp,
    updated_at      timestamp   not null default current_timestamp,
    unique (jockey_code, meet_code)
);

create index if not exists idx_jockeys_meet_code on jockeys (meet_code);
create index if not exists idx_jockeys_name      on jockeys (name);


-- =============================================================================
-- 2. trainers — 조교사
-- =============================================================================
create table if not exists trainers (
    id              bigint      generated by default as identity primary key,
    trainer_code    varchar(20) not null,
    meet_code       varchar(10) not null,
    name            varchar(50) not null,
    eng_name        varchar(100),
    birth_year      integer,
    debut_year      integer,
    affiliation     varchar(10),
    photo_url       text,
    is_active       boolean     not null default true,
    created_at      timestamp   not null default current_timestamp,
    updated_at      timestamp   not null default current_timestamp,
    unique (trainer_code, meet_code)
);

create index if not exists idx_trainers_meet_code on trainers (meet_code);
create index if not exists idx_trainers_name      on trainers (name);


-- =============================================================================
-- 3. race_entries — 경주 출전 정보
-- 한 경주에 여러 말이 출전하고, 각 말마다 기수·조교사·출발 게이트 등이 다릅니다.
-- =============================================================================
create table if not exists race_entries (
    id              bigint          generated by default as identity primary key,
    race_id         bigint          not null references races(id) on delete cascade,
    horse_id        bigint          not null references horses(id),
    jockey_id       bigint          references jockeys(id),
    trainer_id      bigint          references trainers(id),
    -- 출발 게이트 번호 (1~16)
    gate_no         integer         not null,
    -- 마체중 (kg)
    horse_weight    integer,
    -- 전 경주 대비 마체중 변화
    weight_change   integer,
    -- 부담 중량 (kg)
    burden_weight   numeric(5, 1),
    -- 단승식 배당률 (출전 당시 초기값)
    win_odds        numeric(8, 2),
    -- 마사회 API 반환 순위 (출전 순서)
    entry_order     integer,
    -- 게이트 브레이크 여부 (출발 불량 기록)
    -- Phase 2 회의 확정: gate_break 컬럼 필수
    gate_break      boolean         not null default false,
    -- 기수 변경 여부 (알림 트리거 조건)
    jockey_changed  boolean         not null default false,
    created_at      timestamp       not null default current_timestamp,
    updated_at      timestamp       not null default current_timestamp,
    -- 한 경주에 같은 말이 두 번 출전하지 않도록
    unique (race_id, horse_id)
);

create index if not exists idx_race_entries_race    on race_entries (race_id);
create index if not exists idx_race_entries_horse   on race_entries (horse_id);
create index if not exists idx_race_entries_jockey  on race_entries (jockey_id);


-- =============================================================================
-- 4. race_results — 실제 경주 결과
-- 경주 완료 후 마사회 API로 수집되는 실제 순위 및 기록입니다.
-- =============================================================================
create table if not exists race_results (
    id              bigint          generated by default as identity primary key,
    race_id         bigint          not null references races(id) on delete cascade,
    entry_id        bigint          not null references race_entries(id) on delete cascade,
    -- 최종 순위 (1등=1, 실격=99)
    finish_position integer         not null,
    -- 완주 기록 (초)
    finish_time     numeric(8, 3),
    -- 1착마와의 시간차 (초)
    time_behind     numeric(8, 3),
    -- 최종 단승식 배당금 (100원 기준)
    final_odds      numeric(10, 2),
    -- 통과 순위 기록 (JSON 배열: [{"section":1,"position":3}, ...])
    section_times   jsonb,
    created_at      timestamp       not null default current_timestamp,
    unique (race_id, entry_id)
);

create index if not exists idx_race_results_race  on race_results (race_id);
create index if not exists idx_race_results_entry on race_results (entry_id);


-- =============================================================================
-- 5. horse_stats — 말 누적 통계
-- ML 피처 엔지니어링의 핵심 소스입니다.
-- Phase 2 회의 확정: avg_finish_position, top3_rate, avg_odds 필수 포함
-- =============================================================================
create table if not exists horse_stats (
    id                      bigint          generated by default as identity primary key,
    horse_id                bigint          not null references horses(id) on delete cascade,
    -- meet_code 별 통계를 분리 (서울/부산/제주 성적이 다름)
    -- Phase 2 회의 확정: meet_code 일관성 보장
    meet_code               varchar(10)     not null,
    -- 총 출전 횟수
    total_races             integer         not null default 0,
    -- 평균 최종 순위 (낮을수록 좋음)
    avg_finish_position     numeric(5, 2),
    -- Top3 진입률 (0.0 ~ 1.0)
    top3_rate               numeric(5, 4),
    -- 승률 (1위 / 총 출전)
    win_rate                numeric(5, 4),
    -- 평균 단승 배당률
    avg_odds                numeric(8, 2),
    -- 평균 완주 시간 (초)
    avg_finish_time         numeric(8, 3),
    -- 거리별 통계 (JSON: {"1000": {"races":5, "top3":3}, ...})
    distance_stats          jsonb,
    -- 트랙 상태별 통계 (JSON: {"DRY": {"races":10, "top3":6}, ...})
    track_condition_stats   jsonb,
    -- 통계 기준 날짜 (이 날짜까지의 데이터로 계산)
    stats_date              date            not null,
    created_at              timestamp       not null default current_timestamp,
    updated_at              timestamp       not null default current_timestamp,
    unique (horse_id, meet_code, stats_date)
);

create index if not exists idx_horse_stats_horse     on horse_stats (horse_id);
create index if not exists idx_horse_stats_meet_date on horse_stats (meet_code, stats_date);


-- =============================================================================
-- 6. jockey_stats — 기수 누적 통계
-- =============================================================================
create table if not exists jockey_stats (
    id                  bigint          generated by default as identity primary key,
    jockey_id           bigint          not null references jockeys(id) on delete cascade,
    meet_code           varchar(10)     not null,
    total_races         integer         not null default 0,
    avg_finish_position numeric(5, 2),
    top3_rate           numeric(5, 4),
    win_rate            numeric(5, 4),
    stats_date          date            not null,
    created_at          timestamp       not null default current_timestamp,
    updated_at          timestamp       not null default current_timestamp,
    unique (jockey_id, meet_code, stats_date)
);

create index if not exists idx_jockey_stats_jockey on jockey_stats (jockey_id);


-- =============================================================================
-- 7. trainer_stats — 조교사 누적 통계
-- =============================================================================
create table if not exists trainer_stats (
    id                  bigint          generated by default as identity primary key,
    trainer_id          bigint          not null references trainers(id) on delete cascade,
    meet_code           varchar(10)     not null,
    total_races         integer         not null default 0,
    avg_finish_position numeric(5, 2),
    top3_rate           numeric(5, 4),
    win_rate            numeric(5, 4),
    stats_date          date            not null,
    created_at          timestamp       not null default current_timestamp,
    updated_at          timestamp       not null default current_timestamp,
    unique (trainer_id, meet_code, stats_date)
);

create index if not exists idx_trainer_stats_trainer on trainer_stats (trainer_id);


-- =============================================================================
-- 8. odds_history — 배당률 이력
-- 경주 당일 배당률 변동을 시계열로 저장합니다.
-- ML 피처: 배당률 변화율, 스마트 머니 탐지에 사용
-- =============================================================================
create table if not exists odds_history (
    id          bigint          generated by default as identity primary key,
    entry_id    bigint          not null references race_entries(id) on delete cascade,
    -- 배당률 기록 시각
    recorded_at timestamp       not null,
    -- 단승식 배당률
    win_odds    numeric(8, 2)   not null,
    -- 연승식 배당률 (참고용)
    place_odds  numeric(8, 2),
    created_at  timestamp       not null default current_timestamp
);

-- 시계열 쿼리 최적화: entry_id + 시간순 복합 인덱스
create index if not exists idx_odds_history_entry_time on odds_history (entry_id, recorded_at);


-- =============================================================================
-- 9. ml_model_versions — ML 모델 버전 관리
-- Phase 2 회의 확정: ml_feature_store에서 FK로 참조
-- =============================================================================
create table if not exists ml_model_versions (
    id              bigint          generated by default as identity primary key,
    -- 모델 식별자 (예: xgboost_v1, lgbm_v2)
    model_name      varchar(100)    not null,
    version         varchar(50)     not null,
    -- 모델 파일 경로 (S3 또는 로컬)
    model_path      text,
    -- 학습 데이터 기간
    train_from      date,
    train_to        date,
    -- 검증 정확도 (Top-3 기준)
    top3_accuracy   numeric(5, 4),
    -- 모델 하이퍼파라미터 (JSON)
    hyperparameters jsonb,
    -- 현재 서빙 중인 모델 여부
    is_active       boolean         not null default false,
    created_at      timestamp       not null default current_timestamp,
    unique (model_name, version)
);


-- =============================================================================
-- 10. ml_feature_store — ML 피처 스토어
-- Phase 2 회의 확정 사항:
--   - JSONB + 핵심 컬럼 병행 (조회 성능 vs 유연성 균형)
--   - model_version_id FK
--   - computation_status (계산 상태 추적)
--   - error_message (실패 원인 기록)
--   - is_latest (최신 피처 여부)
--   - GIN index on features 컬럼
-- =============================================================================
create table if not exists ml_feature_store (
    id                  bigint          generated by default as identity primary key,
    entry_id            bigint          not null references race_entries(id) on delete cascade,
    model_version_id    bigint          references ml_model_versions(id),
    -- 전체 피처를 JSONB로 저장 (유연성 확보)
    features            jsonb,
    -- 핵심 피처를 별도 컬럼으로도 저장 (쿼리 성능 최적화)
    avg_finish_position numeric(5, 2),
    top3_rate           numeric(5, 4),
    avg_odds            numeric(8, 2),
    -- SHAP 평균 절대값 (피처 중요도 지표)
    -- Phase 2 회의 확정: shap_mean_abs 필수
    shap_mean_abs       numeric(8, 6),
    -- 피처 계산 상태 (PENDING / COMPUTING / DONE / FAILED)
    computation_status  varchar(20)     not null default 'PENDING',
    -- 계산 실패 시 원인 기록
    error_message       text,
    -- 해당 entry의 최신 피처 여부 (재계산 시 이전 레코드는 false)
    is_latest           boolean         not null default true,
    computed_at         timestamp,
    created_at          timestamp       not null default current_timestamp
);

-- JSONB 전체 텍스트 탐색을 위한 GIN 인덱스 (Phase 2 회의 확정)
create index if not exists idx_ml_feature_store_features on ml_feature_store using gin(features);
create index if not exists idx_ml_feature_store_entry    on ml_feature_store (entry_id);
-- is_latest=true 인 레코드만 빠르게 조회하기 위한 부분 인덱스
create index if not exists idx_ml_feature_store_latest   on ml_feature_store (entry_id) where is_latest = true;


-- =============================================================================
-- 11. race_predictions — 예측 결과 (Monte Carlo 포함)
-- Phase 2 Monte Carlo 확정: QMC(Sobol) + Antithetic + Adaptive(10k~100k)
-- =============================================================================
create table if not exists race_predictions (
    id                      bigint          generated by default as identity primary key,
    race_id                 bigint          not null references races(id) on delete cascade,
    entry_id                bigint          not null references race_entries(id) on delete cascade,
    model_version_id        bigint          references ml_model_versions(id),
    -- ML 모델 기본 예측 확률 (0.0 ~ 1.0)
    win_probability         numeric(8, 6),
    top3_probability        numeric(8, 6),
    -- Monte Carlo 시뮬레이션 결과
    mc_win_probability      numeric(8, 6),
    mc_top3_probability     numeric(8, 6),
    -- Monte Carlo 신뢰구간 (± %)
    mc_confidence_interval  numeric(6, 4),
    -- 실제 실행된 시뮬레이션 횟수 (Adaptive: 10k~100k)
    mc_simulation_count     integer,
    -- 예측 신뢰도 점수 (0.0 ~ 1.0, 여러 지표 종합)
    confidence_score        numeric(5, 4),
    -- Counterfactual 분석 결과 (JSON: 가상 시나리오별 확률 변화)
    counterfactual_data     jsonb,
    -- 예측 생성 시각
    predicted_at            timestamp       not null default current_timestamp,
    created_at              timestamp       not null default current_timestamp,
    unique (race_id, entry_id, model_version_id)
);

create index if not exists idx_race_predictions_race   on race_predictions (race_id);
create index if not exists idx_race_predictions_entry  on race_predictions (entry_id);
