-- =============================================================================
-- V7: FastAPI 모델과 DB 스키마 불일치 수정
-- =============================================================================
-- V1~V6가 초기 설계 기준으로 생성됐으나, FastAPI Python 모델과 컬럼명/제약조건이 달라
-- 실데이터 수집 시 ON CONFLICT 오류 및 UndefinedTable 오류가 발생했습니다.
-- 이 마이그레이션이 수정하는 항목:
--   1. races: UNIQUE(meet_code, rc_date, race_no) 제약조건 추가
--   2. race_entries: 컬럼명 정렬 + 누락 컬럼 추가
--   3. ENUM 타입 추가: collect_status, quality_status, data_status, class_change, distance_change
--   4. collection_logs 테이블 생성
--   5. weather_forecasts 테이블 생성
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. races 테이블 UNIQUE 제약조건 추가
-- -----------------------------------------------------------------------------
-- ON CONFLICT (meet_code, rc_date, race_no) DO UPDATE 가 동작하려면
-- 해당 컬럼 조합에 UNIQUE 제약조건이 반드시 필요합니다.
-- -----------------------------------------------------------------------------
ALTER TABLE races
    ADD CONSTRAINT races_meet_code_rc_date_race_no_key
    UNIQUE (meet_code, rc_date, race_no);


-- -----------------------------------------------------------------------------
-- 2. race_entries 컬럼 정렬
-- -----------------------------------------------------------------------------
-- FastAPI RaceEntry 모델 기준으로 컬럼명 변경 및 누락 컬럼 추가.
-- 기존 컬럼: weight_change → horse_weight_diff
--            win_odds     → odds_win
-- -----------------------------------------------------------------------------

-- weight_change → horse_weight_diff 이름 변경
ALTER TABLE race_entries
    RENAME COLUMN weight_change TO horse_weight_diff;

-- win_odds → odds_win 이름 변경
ALTER TABLE race_entries
    RENAME COLUMN win_odds TO odds_win;

-- 누락된 컬럼 추가 (FastAPI 모델에는 있으나 DB에 없는 컬럼들)
ALTER TABLE race_entries
    ADD COLUMN IF NOT EXISTS odds_place        NUMERIC(7, 2),
    ADD COLUMN IF NOT EXISTS rating            NUMERIC(5, 2),
    ADD COLUMN IF NOT EXISTS last_updated      TIMESTAMP,
    ADD COLUMN IF NOT EXISTS next_update       TIMESTAMP,
    ADD COLUMN IF NOT EXISTS is_debut          BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_comeback       BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS rest_days         INTEGER;


-- -----------------------------------------------------------------------------
-- 3. ENUM 타입 추가
-- -----------------------------------------------------------------------------

-- data_status: 수집 상태 (race_entries.data_status 에서 사용)
DO $$
BEGIN
    CREATE TYPE data_status AS ENUM ('READY', 'UPDATING', 'COLLECTED', 'JOCKEY_CHANGED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- class_change: 급조 변동 (race_entries.class_change 에서 사용)
DO $$
BEGIN
    CREATE TYPE class_change AS ENUM ('UP', 'SAME', 'DOWN');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- distance_change: 거리 변동 (race_entries.distance_change 에서 사용)
DO $$
BEGIN
    CREATE TYPE distance_change AS ENUM ('UP', 'SAME', 'DOWN');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- collect_status: 수집 결과 (collection_logs.status 에서 사용)
DO $$
BEGIN
    CREATE TYPE collect_status AS ENUM ('SUCCESS', 'FAILED', 'PARTIAL', 'SKIPPED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- quality_status: 데이터 품질 등급 (collection_logs.quality_status 에서 사용)
DO $$
BEGIN
    CREATE TYPE quality_status AS ENUM ('GOOD', 'WARNING', 'CRITICAL');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;


-- race_entries에 ENUM 컬럼 추가
ALTER TABLE race_entries
    ADD COLUMN IF NOT EXISTS data_status      data_status     NOT NULL DEFAULT 'READY',
    ADD COLUMN IF NOT EXISTS class_change     class_change    NOT NULL DEFAULT 'SAME',
    ADD COLUMN IF NOT EXISTS distance_change  distance_change NOT NULL DEFAULT 'SAME';


-- -----------------------------------------------------------------------------
-- 4. collection_logs 테이블 생성
-- -----------------------------------------------------------------------------
-- FastAPI DataService 가 각 API 수집 결과를 기록하는 테이블입니다.
-- 결측값 비율(null_count), 이상값(anomaly_count), 품질 점수(quality_score) 를
-- 여기에 저장해 실데이터 품질을 추적합니다.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS collection_logs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_name         VARCHAR(100) NOT NULL,
    meet_code        VARCHAR(2),
    rc_date          DATE,
    status           collect_status  NOT NULL,
    records_collected INTEGER,
    error_message    TEXT,
    daily_call_count INTEGER,
    null_count       INTEGER,
    anomaly_count    INTEGER,
    quality_score    NUMERIC(5, 2),
    quality_status   quality_status,
    collected_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_collection_logs_collected_at
    ON collection_logs (collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_collection_logs_api_name
    ON collection_logs (api_name);


-- -----------------------------------------------------------------------------
-- 5. weather_forecasts 테이블 생성
-- -----------------------------------------------------------------------------
-- 기상청 API 에서 수집한 단기/중기 예보를 저장합니다.
-- Monte Carlo 시뮬레이션의 날씨 불확실성 계산에 활용됩니다.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS weather_forecasts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meet_code          VARCHAR(2)   NOT NULL,
    forecast_date      DATE         NOT NULL,
    temp_min           FLOAT,
    temp_max           FLOAT,
    precipitation_prob INTEGER,
    wind_speed         FLOAT,
    condition          VARCHAR(20),
    source             VARCHAR(20)  NOT NULL DEFAULT 'short_term',
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE (meet_code, forecast_date, source)
);

CREATE INDEX IF NOT EXISTS idx_weather_forecasts_meet_date
    ON weather_forecasts (meet_code, forecast_date);
