-- =============================================================================
-- V9: ML/예측/결과 테이블 전면 정렬 — FastAPI 모델 기준
-- =============================================================================
-- FastAPI ORM 모델(ml.py, race.py)과 DB 스키마를 전면 비교한 결과
-- 테이블명/컬럼명/타입 불일치가 다수 발견됨.
-- 실데이터가 아직 없는 개발 단계이므로 데이터 손실 없이 재구성.
-- =============================================================================


-- =============================================================================
-- 1. ml_feature_store 정렬
-- =============================================================================
-- 변경: entry_id → race_entry_id
--       computed_at → calculated_at
-- 추가: race_id, feature_version

-- 외래키 제약 먼저 해제
ALTER TABLE ml_feature_store
    DROP CONSTRAINT IF EXISTS ml_feature_store_entry_id_fkey;

-- 컬럼명 변경
ALTER TABLE ml_feature_store
    RENAME COLUMN entry_id TO race_entry_id;

ALTER TABLE ml_feature_store
    RENAME COLUMN computed_at TO calculated_at;

-- 외래키 재추가
ALTER TABLE ml_feature_store
    ADD CONSTRAINT ml_feature_store_race_entry_id_fkey
    FOREIGN KEY (race_entry_id) REFERENCES race_entries(id) ON DELETE CASCADE;

-- 누락 컬럼 추가
ALTER TABLE ml_feature_store
    ADD COLUMN IF NOT EXISTS race_id        BIGINT REFERENCES races(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS feature_version VARCHAR(20) NOT NULL DEFAULT 'v1.0';

CREATE INDEX IF NOT EXISTS idx_ml_feature_store_race_id
    ON ml_feature_store (race_id);

CREATE INDEX IF NOT EXISTS idx_ml_feature_store_entry_version
    ON ml_feature_store (race_entry_id, feature_version);


-- =============================================================================
-- 2. race_results 정렬
-- =============================================================================
-- 변경: entry_id → race_entry_id
--       finish_position → rank
--       finish_time (numeric) → record_time (varchar)
--       time_behind → margin
--       section_times (jsonb) → section_1~6 (varchar 개별 컬럼)
-- 추가: horse_id

-- 외래키 해제
ALTER TABLE race_results
    DROP CONSTRAINT IF EXISTS race_results_entry_id_fkey;

-- 컬럼명 변경
ALTER TABLE race_results
    RENAME COLUMN entry_id TO race_entry_id;

ALTER TABLE race_results
    RENAME COLUMN finish_position TO rank;

-- finish_time (numeric) → record_time (varchar 20)
ALTER TABLE race_results
    ADD COLUMN IF NOT EXISTS record_time VARCHAR(20);

UPDATE race_results
    SET record_time = finish_time::TEXT
    WHERE finish_time IS NOT NULL;

ALTER TABLE race_results
    DROP COLUMN IF EXISTS finish_time;

-- time_behind → margin
ALTER TABLE race_results
    RENAME COLUMN time_behind TO margin;

-- section_times (jsonb) → section_1 ~ section_6 (varchar 개별 컬럼)
ALTER TABLE race_results
    ADD COLUMN IF NOT EXISTS section_1 VARCHAR(20),
    ADD COLUMN IF NOT EXISTS section_2 VARCHAR(20),
    ADD COLUMN IF NOT EXISTS section_3 VARCHAR(20),
    ADD COLUMN IF NOT EXISTS section_4 VARCHAR(20),
    ADD COLUMN IF NOT EXISTS section_5 VARCHAR(20),
    ADD COLUMN IF NOT EXISTS section_6 VARCHAR(20);

ALTER TABLE race_results
    DROP COLUMN IF EXISTS section_times;

-- horse_id 추가
ALTER TABLE race_results
    ADD COLUMN IF NOT EXISTS horse_id BIGINT REFERENCES horses(id);

-- 외래키 재추가
ALTER TABLE race_results
    ADD CONSTRAINT race_results_race_entry_id_fkey
    FOREIGN KEY (race_entry_id) REFERENCES race_entries(id);


-- =============================================================================
-- 3. race_predictions → predictions (테이블명 변경)
-- =============================================================================
-- FastAPI Prediction 모델이 __tablename__ = "predictions" 사용
-- 기존 race_predictions는 스키마도 다르므로 삭제 후 새로 생성

DROP TABLE IF EXISTS race_predictions CASCADE;

CREATE TABLE IF NOT EXISTS predictions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id         BIGINT NOT NULL REFERENCES races(id) ON DELETE CASCADE,
    race_entry_id   BIGINT NOT NULL REFERENCES race_entries(id) ON DELETE CASCADE,
    model_name      VARCHAR(50)  NOT NULL,
    predicted_rank  INTEGER,
    win_prob        NUMERIC(6, 5),
    place_prob      NUMERIC(6, 5),
    raw_score       NUMERIC(10, 6),
    model_version   VARCHAR(20) NOT NULL DEFAULT 'v1.0',
    predicted_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_predictions_race_id
    ON predictions (race_id);

CREATE INDEX IF NOT EXISTS idx_predictions_race_entry_id
    ON predictions (race_entry_id);


-- =============================================================================
-- 4. ml_model_versions → model_versions (테이블명 + 컬럼 변경)
-- =============================================================================
-- FastAPI ModelVersion 모델이 __tablename__ = "model_versions" 사용
-- train_from → train_start_date
-- train_to   → train_end_date
-- top3_accuracy + hyperparameters → metrics (JSONB)

DROP TABLE IF EXISTS ml_model_versions CASCADE;

CREATE TABLE IF NOT EXISTS model_versions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name       VARCHAR(50)  NOT NULL,
    version          VARCHAR(20)  NOT NULL,
    model_path       TEXT,
    metrics          JSONB        NOT NULL DEFAULT '{}',
    train_start_date DATE,
    train_end_date   DATE,
    is_active        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ml_feature_store의 model_version_id 외래키 업데이트
ALTER TABLE ml_feature_store
    DROP CONSTRAINT IF EXISTS ml_feature_store_model_version_id_fkey;

ALTER TABLE ml_feature_store
    ADD CONSTRAINT ml_feature_store_model_version_id_fkey
    FOREIGN KEY (model_version_id) REFERENCES model_versions(id);


-- =============================================================================
-- 5. ai_commentary 테이블 생성
-- =============================================================================
-- FastAPI AICommentary 모델 기준

CREATE TABLE IF NOT EXISTS ai_commentary (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id           BIGINT NOT NULL REFERENCES races(id) ON DELETE CASCADE,
    type              VARCHAR(10) NOT NULL,           -- 'PRE' 또는 'POST'
    content           TEXT        NOT NULL,
    model_used        VARCHAR(50) NOT NULL DEFAULT 'gpt-4o-mini',
    cache_key         VARCHAR(100) NOT NULL,
    prompt_tokens     INTEGER,
    completion_tokens INTEGER,
    generated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_commentary_race_id
    ON ai_commentary (race_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_commentary_cache_key
    ON ai_commentary (cache_key);


-- =============================================================================
-- 6. odds_history 컬럼명 정렬
-- =============================================================================
-- DB: entry_id, win_odds, place_odds
-- FastAPI OddsHistory(있다면): race_entry_id, odds_win, odds_place 예상

ALTER TABLE odds_history
    DROP CONSTRAINT IF EXISTS odds_history_entry_id_fkey;

ALTER TABLE odds_history
    RENAME COLUMN entry_id TO race_entry_id;

ALTER TABLE odds_history
    RENAME COLUMN win_odds TO odds_win;

ALTER TABLE odds_history
    RENAME COLUMN place_odds TO odds_place;

ALTER TABLE odds_history
    ADD CONSTRAINT odds_history_race_entry_id_fkey
    FOREIGN KEY (race_entry_id) REFERENCES race_entries(id) ON DELETE CASCADE;

-- opening/final 컬럼 추가 (Monte Carlo 스마트머니 탐지용)
ALTER TABLE odds_history
    ADD COLUMN IF NOT EXISTS opening  NUMERIC(7, 2),
    ADD COLUMN IF NOT EXISTS final    NUMERIC(7, 2);
