spring:
  application:
    name: RacePulse
  profiles:
    active: dev  # 개발할 때는 dev, 배포할 때는 prod로 변경

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
